import type { ImportWorkspace } from "./types";

export interface ImportWorkspaceStore { save(workspace: ImportWorkspace): Promise<void>; load(companyId: string): Promise<ImportWorkspace | undefined>; list(): Promise<ImportWorkspace[]>; getActiveCompany(): Promise<string | undefined>; setActiveCompany(id: string): Promise<void>; }
export class MemoryImportWorkspaceStore implements ImportWorkspaceStore { private active?: string; private readonly values = new Map<string, ImportWorkspace>(); async getActiveCompany(){return this.active;} async setActiveCompany(id:string){this.active=id;} async save(workspace: ImportWorkspace) { this.values.set(workspace.company.id, structuredClone(workspace)); } async load(companyId: string) { const value=this.values.get(companyId); return value && structuredClone(value); } async list() { return [...this.values.values()].map((value)=>structuredClone(value)); } }
/** Browser persistence adapter. Raw data stays in IndexedDB and never leaves the browser. */
export class IndexedDbImportWorkspaceStore implements ImportWorkspaceStore {
  private readonly dbName = "finance-dashboard-imports";
  private async db(): Promise<IDBDatabase> { return new Promise((resolve,reject)=>{const request=indexedDB.open(this.dbName,2);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains("workspaces"))request.result.createObjectStore("workspaces",{keyPath:"company.id"});if(!request.result.objectStoreNames.contains("runtime"))request.result.createObjectStore("runtime");};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);}); }
  async getActiveCompany():Promise<string|undefined> {const db=await this.db();return new Promise((resolve,reject)=>{const tx=db.transaction("runtime");const request=tx.objectStore("runtime").get("active-company");request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);tx.oncomplete=()=>db.close();});}
  async setActiveCompany(id:string) {const db=await this.db();await new Promise<void>((resolve,reject)=>{const tx=db.transaction("runtime","readwrite");tx.objectStore("runtime").put(id,"active-company");tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);});}
  async save(workspace: ImportWorkspace) { const db=await this.db(); await new Promise<void>((resolve,reject)=>{const tx=db.transaction("workspaces","readwrite");tx.objectStore("workspaces").put(workspace);tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>{db.close();reject(tx.error);};}); }
  async load(companyId: string) { const db=await this.db(); return new Promise<ImportWorkspace|undefined>((resolve,reject)=>{const request=db.transaction("workspaces").objectStore("workspaces").get(companyId);request.onsuccess=()=>{db.close();resolve(request.result);};request.onerror=()=>{db.close();reject(request.error);};}); }
  async list() { const db=await this.db(); return new Promise<ImportWorkspace[]>((resolve,reject)=>{const request=db.transaction("workspaces").objectStore("workspaces").getAll();request.onsuccess=()=>{db.close();resolve(request.result??[]);};request.onerror=()=>{db.close();reject(request.error);};}); }
}
