import type { ReportingDataset } from "@/domain/data";
import type { Account, FinanceRecord, Period, StatementLine } from "@/domain/models";
import { resolveAccountRule, resolveHierarchyRole } from "./mapping";
import { unpivotWideRows } from "./tableDetection";
import type { FieldMapping, ImportWorkspace, IngestionIssue, IngestionReconciliation, MappingRule, StagedDataset } from "./types";

const text=(v:unknown)=>v==null?"":String(v).trim();
const amount=(v:unknown)=>{const n=Number(String(v??"").replace(/[$,]/g,"").replace(/^\((.*)\)$/,"-$1"));return Number.isFinite(n)?n:NaN;};
const key=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]/g,"");
const cell=(r:Record<string,unknown>,name:string)=>r[Object.keys(r).find(k=>key(k)===key(name))??""];
const finance=(t:string)=>["finance_actual","budget","forecast"].includes(t);
const dataRows=(d:StagedDataset)=>d.wideUnpivot?unpivotWideRows(d.rows,d.wideUnpivot):[...d.rows];
const get=(r:Record<string,unknown>,m:FieldMapping[],f:string)=>r[m.find(x=>x.canonicalField===f&&x.status!=="ignored")?.sourceColumn??""];
const roleLines:Record<string,StatementLine>={grossSales:"revenue",markdowns:"revenue",returns:"revenue",revenue:"revenue",costOfSales:"costOfSales",tradingIncome:"revenue",tradingCost:"costOfSales",operatingCosts:"operatingCosts",depreciationAmortisation:"depreciationAmortisation",interest:"interest",tax:"tax"};
const problem=(datasetId:string,id:string,message:string,n:number):IngestionIssue=>({id:`${datasetId}:${id}`,severity:"error",datasetId,message,affectedRows:n,samples:[],recommendedAction:"Resolve this item in onboarding review."});

export function authoritativeRules(w:ImportWorkspace):MappingRule[]{return w.datasets.filter(d=>(d.confirmedType??d.inferred.type)==="gl_mapping").flatMap(d=>d.rows.flatMap(r=>{const gl=text(cell(r,"GL Code"));if(!gl)return[];const sign=text(cell(r,"Sign Convention")).toLowerCase();return[{id:`auth:${d.id}:${gl}`,companyId:w.company.id,priority:1e6,kind:"exact" as const,value:gl,statement:"pnl" as const,line:"unconfirmed" as const,sign:sign==="cost"?-1:1,sourceMultiplier:sign==="cost"?-1:1,reportingHierarchy:{p1:text(cell(r,"P1 - Section"))||undefined,p2:text(cell(r,"P2 - Header"))||undefined,p3:text(cell(r,"P3 - Sub-Header"))||undefined,pnlSection:text(cell(r,"P&L Section"))||undefined},calculationRole:"unconfirmed" as const,mappingSource:"authoritative_file" as const,mappingSourceFile:w.sources.find(s=>s.id===d.sourceFileId)?.filename,mappingStatus:"Authoritative" as const,confidence:1,authoritative:true}]}));}
export function applyHierarchyRoles(rules:MappingRule[],w:ImportWorkspace):MappingRule[]{return rules.map(rule=>{const node=resolveHierarchyRole(rule.reportingHierarchy??{},w.hierarchyRoles??[]);return node?{...rule,line:node.line||roleLines[node.calculationRole]||"unconfirmed",calculationRole:node.calculationRole,mappingSource:"approved_rule" as const,mappingStatus:node.status}:rule;});}
export function validateWorkspace(w:ImportWorkspace){const out:IngestionIssue[]=[];for(const d of w.datasets){const type=d.confirmedType??d.inferred.type,m=w.mappings.filter(x=>x.datasetId===d.id);if(type==="ignored")continue;if(d.tableRange?.requiresConfirmation&&!d.rangeConfirmed)out.push(problem(d.id,"range","Confirm source table/range before activation.",d.rows.length));if(finance(type)&&!w.scenarios.some(s=>s.datasetId===d.id))out.push(problem(d.id,"scenario","Explicitly confirm a scenario before activation.",d.rows.length));if(finance(type))for(const f of ["accountId","amount"])if(!m.some(x=>x.canonicalField===f&&x.status==="mapped")&&!(d.wideUnpivot&&f==="amount"))out.push(problem(d.id,f,`Map ${f} before activation.`,d.rows.length));}return out;}
export function buildCalendar(w:ImportWorkspace):{periods:Period[];weeks:Period[]}{const d=w.datasets.find(x=>(x.confirmedType??x.inferred.type)==="financial_calendar"),weeks:Period[]=[];if(d)for(const r of dataRows(d)){const no=text(cell(r,"Fiscal Week"))||text(cell(r,"Week")),start=text(cell(r,"Week Start")),end=text(cell(r,"Week End")),fy=text(cell(r,"FY"));if(no&&start&&end)weeks.push({id:`${fy}-W${no.padStart(2,"0")}`,date:end,grain:"week",label:`${fy} W${no}`,shortLabel:`W${no}`,fiscalYear:fy,fiscalPeriod:amount(cell(r,"Fiscal Month"))||0,fiscalWeek:amount(no)||undefined,fiscalQuarter:amount(cell(r,"Fiscal Quarter"))||undefined,externalPeriodToken:text(cell(r,"Fin_Period"))||undefined,weekStart:start,weekEnd:end,calendarYear:new Date(end).getUTCFullYear(),calendarMonth:new Date(end).getUTCMonth()+1,isActual:false});}return{periods:[],weeks};}
export function buildImportedDataset(w:ImportWorkspace):{dataset?:ReportingDataset;issues:IngestionIssue[];reconciliations:IngestionReconciliation[]}{const issues=validateWorkspace(w);if(issues.length)return{issues,reconciliations:[]};const rules=applyHierarchyRoles([...authoritativeRules(w),...w.rules],w),accounts=new Map<string,Account>(),records:FinanceRecord[]=[],magnitude=new Map<string,number>();let raw=0,signed=0,mapped=0,unmapped=0,unresolved=0;for(const d of w.datasets.filter(x=>finance(x.confirmedType??x.inferred.type))){const fm=w.mappings.filter(x=>x.datasetId===d.id),scenario=w.scenarios.find(x=>x.datasetId===d.id)!;for(const [i,r] of dataRows(d).entries()){const id=text(get(r,fm,"accountId")),source=amount(get(r,fm,"amount")??r[d.wideUnpivot?.valueField??"amount"]);if(!id||!Number.isFinite(source))continue;raw+=source;magnitude.set(id,(magnitude.get(id)??0)+Math.abs(source));const rule=resolveAccountRule(id,text(get(r,fm,"accountName")),rules),normal=source*(rule?.sourceMultiplier??1);signed+=normal;if(!rule||rule.line==="unconfirmed"){unmapped+=normal;unresolved+=Math.abs(source);accounts.set(id,{id,name:id,externalId:id,mappingStatus:"unmapped",statement:"pnl",line:"unconfirmed",sign:1,accountMappingStatus:"Needs Review"});continue;}mapped+=normal;accounts.set(id,{id,name:text(get(r,fm,"accountName"))||id,externalId:id,mappingStatus:"mapped",statement:rule.statement,line:rule.line,sign:rule.sign,reportingHierarchy:rule.reportingHierarchy,calculationRole:rule.calculationRole,mappingSource:rule.mappingSource,accountMappingStatus:rule.mappingStatus,sourceMultiplier:rule.sourceMultiplier});records.push({periodId:text(get(r,fm,"period")),entityId:text(get(r,fm,"entityId"))||"company",accountId:id,scenarioValues:[{scenarioId:scenario.scenarioId,value:normal}],...(scenario.kind==="actual"?{actual:normal}:scenario.kind==="budget"?{budget:normal}:{forecast:normal}),lineage:{sourceImportId:d.sourceFileId,sourceRow:i+1,mappingVersion:rule.id}});}}
const totalMagnitude=[...magnitude.values()].reduce((s,v)=>s+v,0),threshold=Math.max(1,totalMagnitude*.001);if(unresolved>=threshold)issues.push(problem("finance","canonical-role",`Material unresolved canonical roles: ${unresolved.toFixed(2)} magnitude.`,1));if(issues.length)return{issues,reconciliations:[]};const {periods,weeks}=buildCalendar(w),gls=magnitude.size,mappedGls=[...accounts.values()].filter(a=>a.mappingStatus==="mapped").length,valueCoverage=totalMagnitude? [...magnitude.entries()].filter(([id])=>accounts.get(id)?.mappingStatus==="mapped").reduce((s,[,v])=>s+v,0)/totalMagnitude:0;const rec=(id:string,label:string,a:number,b:number,stage:IngestionReconciliation["stage"]):IngestionReconciliation=>({id,label,sourceTotal:a,targetTotal:b,difference:a-b,tolerance:.01,status:Math.abs(a-b)<.01?"Reconciled":"Exception",stage});const reconciliations=[rec("raw-sign","Raw source → sign normalised (explained multiplier)",raw,signed,"sign"),rec("sign-mapped","Sign normalised → mapped + unmapped",signed,mapped+unmapped,"mapped"),rec("mapped-canonical","Mapped → canonical",mapped,mapped,"canonical")];const caps={hasPnl:records.length>0,hasBalanceSheet:false,hasCashFlow:false,hasSales:false,hasWeeklySales:false,hasBudget:records.some(r=>r.budget!==undefined),hasForecast:records.some(r=>r.forecast!==undefined),hasOperationalKpis:false};const dataset:ReportingDataset={id:`import:${w.company.id}:${Date.now()}`,source:"import",periods,weeks,dimensions:{entities:[{id:"company",name:w.company.profile.companyName,level:0}],accounts:[...accounts.values()],departments:[],costCentres:[],locations:[],channels:[],products:[],customers:[]},financeRecords:records,salesRecords:[],weeklySalesRecords:[],operationalRecords:[],cashFlowRecords:[],scenarios:w.scenarios.map(s=>({id:s.scenarioId,kind:s.kind,label:s.label,version:s.version})),currentPeriodId:periods.at(-1)?.id??"",defaultEntityId:"company",profile:w.company.profile,scenarioRoles:{actual:"actual",budget:"budget",forecast:"forecast"},capabilities:caps,dataQuality:{mappingSummaries:[{dimension:"GL Accounts",total:gls,mapped:mappedGls,unmapped:gls-mappedGls,review:0,valueCoverage}],unmappedMembers:[],issues:[],reconciliations:reconciliations.map(x=>({id:x.id,statement:x.label,sourceTotal:x.sourceTotal,mappedTotal:x.targetTotal,difference:x.difference,tolerance:x.tolerance,status:x.status})),imports:[],health:{integrityScore:Math.round(valueCoverage*100)}}};return{dataset,issues,reconciliations};}
export class ImportedCompanyAdapter {readonly id:string;private readonly workspace:ImportWorkspace;constructor(workspace:ImportWorkspace){this.workspace=workspace;this.id=`imported:${workspace.company.id}`;}load(){const result=buildImportedDataset(this.workspace);if(!result.dataset)throw new Error("Imported company has blocking validation errors.");return result.dataset;}}
