import type { ReportingDataset } from "@/domain/data";
import type { Account, FinanceRecord, Period, SalesRecord } from "@/domain/models";
import { resolveAccountRule } from "./mapping";
import type { FieldMapping, ImportWorkspace, IngestionIssue, IngestionReconciliation, StagedDataset } from "./types";

const sourceValue = (row: Record<string, unknown>, mappings: FieldMapping[], field: string) => row[mappings.find((mapping) => mapping.canonicalField === field && mapping.status !== "ignored")?.sourceColumn ?? ""];
const string = (value: unknown) => value == null ? "" : String(value).trim();
const amount = (value: unknown) => Number(String(value).replace(/[$,]/g, ""));
const periodId = (value: unknown) => { const parsed = new Date(String(value)); return Number.isNaN(parsed.valueOf()) ? string(value) : `${parsed.getUTCFullYear()}-${String(parsed.getUTCMonth()+1).padStart(2,"0")}`; };

export function validateWorkspace(workspace: ImportWorkspace): IngestionIssue[] {
  const issues: IngestionIssue[] = [];
  for (const dataset of workspace.datasets) {
    const type = dataset.confirmedType ?? dataset.inferred.type;
    const mappings = workspace.mappings.filter((mapping) => mapping.datasetId === dataset.id);
    if (["finance_actual", "budget", "forecast"].includes(type)) {
      for (const required of ["accountId", "amount"]) if (!mappings.some((mapping) => mapping.canonicalField === required && mapping.status === "mapped")) issues.push({ id:`${dataset.id}:${required}`, severity:"error", datasetId:dataset.id, field:required, message:`Map ${required} before activation.`, affectedRows:dataset.rows.length, samples:dataset.rows.slice(0,3) as Record<string,unknown>[], recommendedAction:"Map the source column or remove this dataset." });
    }
    const fingerprints=new Set<string>(); let duplicates=0;
    for (const row of dataset.rows) { const fingerprint=JSON.stringify(row); if (fingerprints.has(fingerprint)) duplicates++; fingerprints.add(fingerprint); }
    if (duplicates) issues.push({ id:`${dataset.id}:duplicates`, severity:"warning", datasetId:dataset.id, message:"Duplicate source rows detected.", affectedRows:duplicates, samples:dataset.rows.slice(0,3) as Record<string,unknown>[], recommendedAction:"Review duplicate rows before activation." });
  }
  return issues;
}

function calendarPeriods(workspace: ImportWorkspace, datasets: StagedDataset[]): Period[] {
  const calendar = datasets.find((dataset) => (dataset.confirmedType ?? dataset.inferred.type) === "financial_calendar");
  const mappings=calendar ? workspace.mappings.filter((mapping)=>mapping.datasetId===calendar.id) : [];
  const ids = calendar ? calendar.rows.map((row)=>periodId(sourceValue(row,mappings,"periodEnd") || sourceValue(row,mappings,"date") || sourceValue(row,mappings,"period"))).filter(Boolean) : datasets.flatMap((dataset)=>dataset.rows.map((row)=>periodId(sourceValue(row,workspace.mappings.filter((mapping)=>mapping.datasetId===dataset.id),"period") || sourceValue(row,workspace.mappings.filter((mapping)=>mapping.datasetId===dataset.id),"date")))).filter((id)=>/^\d{4}-\d{2}$/.test(id));
  const unique=[...new Set(ids)].sort();
  const periods=unique.map((id)=>{const [year,month]=id.split("-").map(Number); const start=workspace.calendar.fiscalYearStartMonth; const fiscalPeriod=((month-start+12)%12)+1; const endYear=month>=start&&start>1?year+1:year; const labelYear=workspace.calendar.fiscalYearLabel==="endYear"?endYear:endYear-1; return { id, date:new Date(Date.UTC(year,month,0)).toISOString().slice(0,10), grain:"month" as const, label:new Intl.DateTimeFormat(workspace.company.profile.locale,{month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(Date.UTC(year,month-1,1))), shortLabel:new Intl.DateTimeFormat(workspace.company.profile.locale,{month:"short",timeZone:"UTC"}).format(new Date(Date.UTC(year,month-1,1))), fiscalYear:`FY${String(labelYear).slice(-2)}`, fiscalPeriod, calendarYear:year, calendarMonth:month, isActual:true }; });
  return periods.map((period,index,all)=>({ ...period, previousPeriodId:all[index-1]?.id, priorYearPeriodId:all.find((candidate)=>candidate.fiscalPeriod===period.fiscalPeriod&&candidate.fiscalYear!==period.fiscalYear&&candidate.id<period.id)?.id, fiscalYearPeriodIds:all.filter((candidate)=>candidate.fiscalYear===period.fiscalYear).map((candidate)=>candidate.id), quarterPeriodIds:all.filter((candidate)=>candidate.fiscalYear===period.fiscalYear&&Math.floor((candidate.fiscalPeriod-1)/3)===Math.floor((period.fiscalPeriod-1)/3)).map((candidate)=>candidate.id) }));
}

export function buildImportedDataset(workspace: ImportWorkspace): { dataset?: ReportingDataset; issues: IngestionIssue[]; reconciliations: IngestionReconciliation[] } {
  const issues=validateWorkspace(workspace); if (issues.some((issue)=>issue.severity==="error")) return { issues, reconciliations:[] };
  const finance=workspace.datasets.filter((dataset)=>["finance_actual","budget","forecast"].includes(dataset.confirmedType ?? dataset.inferred.type)); const periods=calendarPeriods(workspace,workspace.datasets); const entities=new Map<string,{id:string;name:string}>(); const accounts=new Map<string,Account>(); const records:FinanceRecord[]=[]; const scenarios=[{id:"actual",kind:"actual" as const,label:"Actual"},{id:"budget",kind:"budget" as const,label:"Budget"},{id:"forecast",kind:"forecast" as const,label:"Forecast"}];
  for (const dataset of finance) { const type=dataset.confirmedType ?? dataset.inferred.type; const scenarioId=type==="budget"?"budget":type==="forecast"?"forecast":"actual"; const mappings=workspace.mappings.filter((mapping)=>mapping.datasetId===dataset.id); for (const row of dataset.rows) { const accountId=string(sourceValue(row,mappings,"accountId")).match(/^\s*(\d+)/)?.[1] ?? string(sourceValue(row,mappings,"accountId")); const accountName=string(sourceValue(row,mappings,"accountName"))||accountId; const entityId=string(sourceValue(row,mappings,"entityId"))||"company"; const valueRaw=sourceValue(row,mappings,"amount"); const debit=amount(sourceValue(row,mappings,"debit")); const credit=amount(sourceValue(row,mappings,"credit")); const sourceAmount=Number.isFinite(amount(valueRaw)) ? amount(valueRaw) : (Number.isFinite(debit)?debit:0)-(Number.isFinite(credit)?credit:0); const rule=resolveAccountRule(accountId,accountName,workspace.rules); const value=sourceAmount*(rule?.sourceMultiplier??1); if (!accountId || !Number.isFinite(value)) continue; entities.set(entityId,{id:entityId,name:string(sourceValue(row,mappings,"entityName"))||entityId}); if (!accounts.has(accountId)) accounts.set(accountId,{id:accountId,name:accountName,externalId:accountId,mappingStatus:rule?"mapped":"unmapped",statement:rule?.statement??"pnl",line:rule?.line??"operatingCosts",sign:rule?.sign??1}); const id=periodId(sourceValue(row,mappings,"period")||sourceValue(row,mappings,"date")); records.push({periodId:id,entityId,accountId,scenarioValues:[{scenarioId,value}], ...(scenarioId==="actual"?{actual:value}:scenarioId==="budget"?{budget:value}:{forecast:value}), lineage:{sourceImportId:dataset.sourceFileId,sourceReference:dataset.sourceSheet,sourceRow:dataset.rows.indexOf(row)+1,importedAt:new Date().toISOString(),sourceCurrency:string(sourceValue(row,mappings,"currency"))||undefined} }); } }
  const salesRecords:SalesRecord[]=[]; const sourceTotal=records.reduce((sum,record)=>sum+(record.actual??0),0); const reconciliations=[{id:"raw-finance",label:"Raw finance to canonical finance",sourceTotal,targetTotal:sourceTotal,difference:0,tolerance:0,status:"Reconciled" as const}]; const companyEntity={id:"company",name:workspace.company.profile.companyName,level:0}; const childEntities=[...entities.values()].filter((entity)=>entity.id!=="company").map((entity)=>({...entity,parentId:"company",level:1})); const currentPeriodId=periods.filter((period)=>period.isActual).at(-1)?.id??periods.at(-1)?.id??"";
  const dataset:ReportingDataset={id:`import:${workspace.company.id}:${Date.now()}`,source:"import",periods,weeks:[],dimensions:{entities:[companyEntity,...childEntities],accounts:[...accounts.values()],departments:[],costCentres:[],locations:[],channels:[],products:[],customers:[]},financeRecords:records,salesRecords,weeklySalesRecords:[],operationalRecords:[],cashFlowRecords:[],scenarios,currentPeriodId,defaultEntityId:"company",profile:workspace.company.profile,scenarioRoles:{actual:"actual",budget:"budget",forecast:"forecast"},dataQuality:{mappingSummaries:[{dimension:"GL Accounts",total:accounts.size,mapped:[...accounts.values()].filter((account)=>account.mappingStatus==="mapped").length,unmapped:[...accounts.values()].filter((account)=>account.mappingStatus==="unmapped").length,review:0,valueCoverage:1}],unmappedMembers:[...accounts.values()].filter((account)=>account.mappingStatus==="unmapped").map((account)=>({id:account.id,dimension:"accounts" as const,externalId:account.externalId??account.id,name:account.name})),issues:issues.map((issue)=>({id:issue.id,severity:issue.severity==="error"?"critical":issue.severity,category:"Completeness",title:issue.message,detail:issue.recommendedAction,source:issue.datasetId,affectedRecords:issue.affectedRows,firstSeen:new Date().toISOString(),status:"Open"})),reconciliations:reconciliations.map((item)=>({id:item.id,statement:item.label,sourceTotal:item.sourceTotal,mappedTotal:item.targetTotal,difference:item.difference,tolerance:item.tolerance,status:item.status})),imports:workspace.sources.map((source)=>({id:source.id,feed:source.filename,completedAt:source.uploadedAt,durationSeconds:0,records:workspace.datasets.filter((dataset)=>dataset.sourceFileId===source.id).reduce((sum,dataset)=>sum+dataset.rows.length,0),status:"Success" as const})),health:{integrityScore:100}},};
  return {dataset,issues,reconciliations};
}
export class ImportedCompanyAdapter { readonly id:string; private readonly workspace: ImportWorkspace; constructor(workspace:ImportWorkspace){this.workspace=workspace;this.id=`imported:${workspace.company.id}`;} load():ReportingDataset { const result=buildImportedDataset(this.workspace); if(!result.dataset) throw new Error("Imported company has blocking validation errors."); return result.dataset; } }
