import type { ImportWorkspace } from "@/domain/ingestion/types";
import { buildImportedDataset, authoritativeRules } from "@/domain/ingestion/transform";
import { resolveHierarchyRole } from "@/domain/ingestion/mapping";
import { capabilityLabels } from "@/domain/selectors/availability";
import { Panel, PanelHeader, PanelBody } from "@/components/ui/Panel";
import { activationBlockers } from "@/domain/data/runtime";
export { activationBlockers } from "@/domain/data/runtime";

export type ActivationResult = ReturnType<typeof buildImportedDataset>;

/** Counts configuration only; financial coverage/totals are exclusively production outputs. */
export function ActivationReview({ workspace, result }: { workspace: ImportWorkspace; result: ActivationResult }) {
  const data = result.dataset;
  const rules = authoritativeRules(workspace);
  const nodes = [...new Map(rules.filter(rule => rule.reportingHierarchy).map(rule => [JSON.stringify(rule.reportingHierarchy), rule.reportingHierarchy!])).values()];
  const resolved = nodes.map(node => ({ node, role: resolveHierarchyRole(node, workspace.hierarchyRoles ?? []) }));
  const explicit = resolved.filter(({node, role}) => role && role.p1 === node.p1 && role.p2 === node.p2 && role.p3 === node.p3).length;
  const unresolved = resolved.filter(item => !item.role || item.role.calculationRole === "unconfirmed").length;
  const blockers = activationBlockers(result);
  const warnings = result.issues.filter(issue => issue.severity !== "error");
  const number = (value: number) => value.toLocaleString(workspace.company.profile.locale, { maximumFractionDigits: 2 });
  const calendars = workspace.datasets.filter(source => (source.confirmedType ?? source.inferred.type) === "financial_calendar");
  return <section id="activation-review" className="mt-4" aria-label="Activation review"><Panel><PanelHeader title="Activation review" meta={workspace.activatedDataset ? "Previously activated · review changes before reactivation" : "Review before making this company live"}/><PanelBody>
    <div className="grid gap-4 text-xs md:grid-cols-2">
      <div><h3 className="font-semibold">Company</h3><p>{workspace.company.profile.companyName} · {workspace.company.profile.reportingCurrency}</p><p>{workspace.company.profile.fiscalCalendar.periodicity} · fiscal year starts month {workspace.company.profile.fiscalCalendar.fiscalYearStartMonth}</p><p>Reporting range: {data?.periods[0]?.label ?? "Unavailable"} — {data?.periods.at(-1)?.label ?? "Unavailable"}</p></div>
      <div><h3 className="font-semibold">Field mappings</h3><p>{workspace.mappings.filter(mapping => mapping.status === "mapped").length} mapped/confirmed · {workspace.mappings.filter(mapping => mapping.status === "ignored").length} ignored · {workspace.mappings.filter(mapping => mapping.status === "review").length} need review</p><p>Unresolved required mappings appear in production blockers below.</p></div>
      <div><h3 className="font-semibold">Finance / GL mapping</h3>{data?.dataQuality.mappingSummaries.map(summary => <p key={summary.dimension}>{summary.total} GLs detected · {summary.mapped} mapped · {summary.unmapped} unresolved · count {summary.total ? number(summary.mapped / summary.total * 100) : "—"}% · magnitude {number(summary.valueCoverage * 100)}%</p>) ?? <p>Coverage unavailable until production validation completes.</p>}<p>{rules.length} authoritative mapping definitions · {workspace.rules.filter(rule => rule.mappingSource !== "manual").length} configured rules · {workspace.rules.filter(rule => rule.mappingSource === "manual").length} manual definitions</p><p className="text-tertiary">Mapping definitions are not detected-account coverage by provenance; that breakdown is not emitted by the engine.</p></div>
      <div><h3 className="font-semibold">Hierarchy roles</h3><p>{nodes.length} source hierarchy paths · {explicit} explicit · {resolved.length - explicit - unresolved} inherited · {unresolved} unresolved</p><p>Material unresolved amounts: see production blockers. Per-node materiality is not exposed by the current engine.</p><a className="underline" href="#hierarchy-review">Review hierarchy assignments</a></div>
      <div><h3 className="font-semibold">Confirmed scenarios</h3>{workspace.scenarios.length ? workspace.scenarios.map(scenario => <p key={scenario.datasetId}>{scenario.kind} · {scenario.label} · {scenario.version ?? "No version"} · {scenario.scenarioId}</p>) : <p>None confirmed</p>}</div>
      <div><h3 className="font-semibold">Calendar</h3><p>{data?.periods.length ?? "Unavailable"} monthly periods · {data?.weeks.length ?? "Unavailable"} fiscal weeks</p><p>Sources: {calendars.map(calendar => calendar.sourceSheet ?? calendar.id).join(", ") || "Finance period tokens"}</p><p>Prior-year relationships: {data?.periods.filter(period => period.priorYearPeriodId).length ?? 0} months · {data?.weeks.filter(week => week.priorYearPeriodId).length ?? 0} weeks</p><p>Unresolved tokens are listed in production validation below.</p></div>
      <div><h3 className="font-semibold">Sales</h3><p>{data?.salesRecords.length ?? "Unavailable"} monthly rows · {data?.weeklySalesRecords.length ?? "Unavailable"} weekly rows</p><p>{data?.dimensions.entities.length ?? "—"} entity members (including root) · {data?.dimensions.channels.length ?? "—"} channels · {data?.dimensions.locations.length ?? "—"} locations</p></div>
      <div><h3 className="font-semibold">Capabilities</h3>{data?.capabilities ? Object.entries(capabilityLabels).map(([key,label]) => <span key={key} className="mr-3 inline-block">{label} {data.capabilities?.[key as keyof typeof capabilityLabels] ? "✓" : "—"}</span>) : <p>Unavailable until a valid canonical dataset is constructed.</p>}</div>
    </div>
    <h3 className="mt-4 text-xs font-semibold">Active sources</h3><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="type-table-head"><tr><th className="pb-2 pr-3">Source / sheet</th><th>Classification</th><th>Selected range</th><th>Rows</th><th>Status</th></tr></thead><tbody>{workspace.datasets.filter(source => (source.confirmedType ?? source.inferred.type) !== "ignored").map(source => <tr key={source.id} className="border-t border-subtle"><td className="py-2"><a className="underline" href={`#review-${source.id}`}>{workspace.sources.find(file => file.id === source.sourceFileId)?.filename ?? source.sourceFileId} / {source.sourceSheet}</a></td><td>{source.confirmedType ?? `${source.inferred.type} (suggested)`}</td><td>{source.tableRange ? `Header ${source.tableRange.headerRow}; rows ${source.tableRange.startRow}–${source.tableRange.endRow}; columns ${source.tableRange.startColumn ?? 1}–${source.tableRange.endColumn ?? source.columns.length}` : "Staged source"}</td><td>{source.rows.length}</td><td>{source.tableRange?.requiresConfirmation && !source.rangeConfirmed ? "Range confirmation required" : source.status}</td></tr>)}</tbody></table></div>
    <h3 className="mt-4 text-xs font-semibold">Reconciliation evidence</h3>
    {!result.reconciliations.length && <p className="text-xs text-secondary">Not available while production validation is blocked.</p>}
    {result.reconciliations.map(check => <div key={check.id} className="mt-2 border-t border-subtle pt-2 text-xs"><p>{check.label}: {number(check.sourceTotal)} → {number(check.targetTotal)} · difference {number(check.difference)} · tolerance {check.tolerance}</p><p>{check.stage === "sign" ? `Explained sign adjustment ${number(check.transformationAdjustment ?? 0)} · expected ${number(check.expectedTotal ?? check.targetTotal)} · ${check.status}.` : check.status === "unavailable" ? "Independent evidence unavailable." : check.status === "fail" ? "Reconciliation failure — review required." : `${check.status} · ${check.sourceRowCount ?? 0} source rows / ${check.targetRowCount ?? 0} target rows.`}</p><p className="text-tertiary">{check.sourceFileId}{check.sourceSheet ? ` / ${check.sourceSheet}` : ""} · scenario {check.scenarioId} · periods {check.periodScope?.join(", ") || "—"}</p></div>)}
    <div className="mt-4 text-xs"><h3 className="font-semibold">Warnings / blocking issues</h3>{warnings.map((issue,index) => <p key={`${issue.id}-${index}`}>{issue.message}</p>)}{blockers.length ? <ul className="text-negative" role="alert">{blockers.map((message,index) => <li key={index}><a href={result.issues[index]?.datasetId ? `#review-${result.issues[index].datasetId}` : "#hierarchy-review"}>{message}</a></li>)}</ul> : <p>0 production blockers. Review the evidence limitations above before activating.</p>}</div>
  </PanelBody></Panel></section>;
}
