import { Badge } from "@/components/ui/Badge";
import type { CanonicalField, DatasetType, ImportWorkspace, StagedDataset } from "@/domain/ingestion";
import { updateWorkspaceFieldMapping } from "./reviewState";

const fields:CanonicalField[]=["period","date","entityId","entityName","accountId","accountName","costCentreId","departmentId","amount","debit","credit","currency","revenue","cost","units","orders","locationId","channelId","productId","customerId","metricId","value","ignore"];
export function DatasetReview({dataset,workspace,onChange,onRangeChange}:{dataset:StagedDataset;workspace:ImportWorkspace;onChange:(workspace:ImportWorkspace)=>void;onRangeChange:(field:"headerRow"|"startRow"|"endRow"|"startColumn"|"endColumn",value:number)=>void}){
 const type=dataset.confirmedType??dataset.inferred.type,range=dataset.tableRange;
 const update=(fn:(current:ImportWorkspace)=>ImportWorkspace)=>onChange(fn(workspace));
 return <section className="mb-3 border border-subtle p-3 text-[12px] text-secondary"><div className="flex flex-wrap justify-between gap-2"><span className="text-primary">{workspace.sources.find(source=>source.id===dataset.sourceFileId)?.filename} · {dataset.sourceSheet} · {dataset.rows.length.toLocaleString()} rows</span><Badge tone={range?.requiresConfirmation&&!dataset.rangeConfirmed?"caution":"neutral"}>{dataset.inferred.type} · {Math.round(dataset.inferred.confidence*100)}%</Badge></div><div className="mt-2 flex flex-wrap gap-3"><label>Dataset type <select className="ml-1 border border-subtle bg-canvas p-1" value={type} onChange={event=>update(current=>({...current,datasets:current.datasets.map(item=>item.id===dataset.id?{...item,confirmedType:event.target.value as DatasetType}:item)}))}>{(["finance_actual","budget","forecast","sales","financial_calendar","gl_mapping","ignored","unknown"] as DatasetType[]).map(item=><option key={item}>{item}</option>)}</select></label><span>{dataset.inferred.reasons.join("; ")}</span></div>
 {range&&<div className="mt-2 bg-inset p-2"><div className="flex flex-wrap gap-2">{(["headerRow","startRow","endRow","startColumn","endColumn"] as const).map(field=><label key={field}>{field}<input aria-label={field} className="ml-1 w-14 border border-line bg-panel px-1.5 py-1" type="number" min="1" value={range[field]??1} onChange={event=>onRangeChange(field,Number(event.target.value))}/></label>)}<Badge tone={dataset.rangeConfirmed?"positive":range.requiresConfirmation?"caution":"neutral"}>{dataset.rangeConfirmed?"Confirmed":range.requiresConfirmation?"Needs Review":"Auto-detected"}</Badge>{range.requiresConfirmation&&!dataset.rangeConfirmed&&<button className="border border-line px-2 py-1 hover:border-strong" onClick={()=>update(current=>({...current,datasets:current.datasets.map(item=>item.id===dataset.id?{...item,rangeConfirmed:true}:item)}))}>Confirm selected range</button>}</div><div aria-label="Raw worksheet preview" className="mt-2 max-h-28 overflow-auto font-mono text-[10px]">{(dataset.rawGrid??[]).slice(Math.max(0,range.headerRow-2),Math.min(dataset.rawGrid?.length??0,range.endRow+2)).map((row,index)=>{const rowNumber=Math.max(0,range.headerRow-2)+index+1;return <div key={rowNumber} className={`${rowNumber===range.headerRow?"bg-accent-soft font-bold text-primary":""} ${rowNumber>=range.startRow&&rowNumber<=range.endRow?"text-secondary":"text-tertiary"}`}>{rowNumber}: {JSON.stringify(row.slice((range.startColumn??1)-1,range.endColumn))}</div>;})}</div></div>}
 {(["finance_actual","budget","forecast"] as DatasetType[]).includes(type)&&<div className="mt-2 flex flex-wrap items-center gap-2">Scenario <select aria-label="Scenario" className="border border-line bg-panel px-1.5 py-1" value={workspace.scenarios.find(scenario=>scenario.datasetId===dataset.id)?.kind??""} onChange={event=>{const kind=event.target.value as "actual"|"budget"|"forecast";update(current=>({...current,scenarios:[...current.scenarios.filter(s=>s.datasetId!==dataset.id),{datasetId:dataset.id,scenarioId:kind,kind,label:kind==="budget"?"Original Budget":kind,version:kind==="budget"?"Original Budget":undefined}]}));}}><option value="">Confirm scenario…</option><option value="actual">Actual</option><option value="budget">Budget / Original Budget</option><option value="forecast">Forecast</option></select><Badge tone={workspace.scenarios.some(s=>s.datasetId===dataset.id)?"positive":"caution"}>{workspace.scenarios.some(s=>s.datasetId===dataset.id)?"Confirmed":"Required"}</Badge></div>}
 <details className="mt-2"><summary className="cursor-pointer text-primary">Field mapping review ({dataset.columns.length})</summary><div className="mt-2 max-h-64 overflow-auto"><table className="w-full text-left"><thead className="type-table-head"><tr><th className="pb-2 pr-3">Source column</th><th>Type</th><th>Canonical field</th><th>Confidence</th><th>Status</th><th>Samples</th></tr></thead><tbody>{dataset.columns.map(column=>{const mapping=workspace.mappings.find(item=>item.datasetId===dataset.id&&item.sourceColumn===column.name);return <tr key={column.name} className="border-t border-subtle"><td>{column.name}</td><td>{column.inferredType}</td><td><select aria-label={`Canonical field for ${column.name}`} className="border border-line bg-panel px-1.5 py-1" value={mapping?.canonicalField??"ignore"} onChange={event=>mapping&&update(current=>updateWorkspaceFieldMapping(current,mapping.id,event.target.value as CanonicalField))}>{fields.map(field=><option key={field}>{field}</option>)}</select></td><td>{mapping?.confidence?`${Math.round(mapping.confidence*100)}%`:"—"}</td><td>{mapping?.status??"Suggested"}</td><td>{column.samples.slice(0,2).map(String).join(", ")}</td></tr>;})}</tbody></table></div></details>
 </section>;
}
