import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Upload } from "lucide-react";
import { Panel, PanelBody, PanelHeader } from "@/components/ui/Panel";
import { Badge } from "@/components/ui/Badge";
import { buildImportedDataset, IndexedDbImportWorkspaceStore, restageDatasetRange, stageLocalFile, suggestFieldMappings, type CanonicalField, type DatasetType, type ImportWorkspace, type IngestionCompany } from "@/domain/ingestion";
import { useReportingDataController } from "@/app/providers/ReportingDataProvider";
import { HierarchyRoleReview } from "./HierarchyRoleReview";

const fields:CanonicalField[]=["period","date","entityId","entityName","accountId","accountName","costCentreId","departmentId","amount","debit","credit","currency","revenue","cost","units","orders","locationId","channelId","productId","customerId","metricId","value","ignore"];
const makeCompany=():IngestionCompany=>({id:crypto.randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),profile:{companyName:"New company",shortName:"New company",reportingCurrency:"AUD",currencySymbol:"$",locale:"en-AU",defaultScale:"millions",fiscalCalendar:{periodicity:"monthly",fiscalYearStartMonth:1,fiscalYearLabel:"endYear"}}});
const emptyWorkspace=(company:IngestionCompany):ImportWorkspace=>({company,sources:[],datasets:[],mappings:[],rules:[],hierarchyRoles:[],customDimensions:[],scenarios:[],calendar:{fiscalYearStartMonth:1,fiscalYearLabel:"endYear"},issues:[],reconciliations:[]});

export function OnboardingPanel(){
  const {activateDataset,activateDefaultDataset}=useReportingDataController();
  const [company,setCompany]=useState(makeCompany);
  const [workspace,setWorkspace]=useState<ImportWorkspace>(()=>emptyWorkspace(company));
  const store=useMemo(()=>new IndexedDbImportWorkspaceStore(),[]);
  const [saved,setSaved]=useState<ImportWorkspace[]>([]);
  useEffect(()=>{void store.list().then(setSaved);},[store]);
  useEffect(()=>{void store.save({...workspace,company});},[workspace,company,store]);
  const result=useMemo(()=>buildImportedDataset({...workspace,company}),[workspace,company]);
  const updateDataset=(id:string,fn:(d:ImportWorkspace["datasets"][number])=>ImportWorkspace["datasets"][number])=>setWorkspace(w=>({...w,datasets:w.datasets.map(d=>d.id===id?fn(d):d)}));
  const upload=async(files:FileList|null)=>{if(!files)return;const staged=await Promise.all([...files].map(file=>stageLocalFile(company.id,file)));setWorkspace(w=>({...w,sources:[...w.sources,...staged.map(x=>x.source)],datasets:[...w.datasets,...staged.flatMap(x=>x.datasets)],mappings:[...w.mappings,...staged.flatMap(x=>x.datasets.flatMap(d=>suggestFieldMappings(d.id,d.columns.map(c=>c.name))))]}));};
  const changeRange=(datasetId:string,field:"headerRow"|"startRow"|"endRow"|"startColumn"|"endColumn",value:number)=>setWorkspace(w=>{const old=w.datasets.find(d=>d.id===datasetId)!;const next=restageDatasetRange(old,{...old.tableRange!,[field]:value,requiresConfirmation:true});const names=new Set(next.columns.map(c=>c.name));const existing=w.mappings.filter(m=>m.datasetId===datasetId);const surviving=existing.filter(m=>names.has(m.sourceColumn));const suggestions=suggestFieldMappings(datasetId,next.columns.map(c=>c.name)).filter(m=>!surviving.some(x=>x.sourceColumn===m.sourceColumn));const removed=existing.filter(m=>!names.has(m.sourceColumn)).map(m=>({...m,status:"review" as const}));return{...w,datasets:w.datasets.map(d=>d.id===datasetId?{...next,rangeConfirmed:false}:d),mappings:[...w.mappings.filter(m=>m.datasetId!==datasetId),...surviving,...removed,...suggestions]};});
  const blockers=result.issues.filter(issue=>issue.severity==="error");
  return <Panel><PanelHeader title="Company onboarding" meta="Local staging · review · validation · activation"/><PanelBody>
    <div className="mb-4 flex flex-wrap items-end gap-3"><label className="text-[11px] text-secondary">Company<input className="mt-1 block h-8 w-48 rounded border border-subtle bg-canvas px-2 text-primary" value={company.profile.companyName} onChange={e=>setCompany({...company,profile:{...company.profile,companyName:e.target.value,shortName:e.target.value}})}/></label><label className="inline-flex h-8 items-center gap-2 rounded border border-subtle px-3 text-[12px] text-secondary cursor-pointer"><Upload size={14}/> Upload CSV / XLSX<input className="hidden" type="file" accept=".csv,.xlsx,.xls" multiple onChange={e=>void upload(e.target.files)}/></label><button className="h-8 rounded border border-subtle px-3 text-[12px]" onClick={()=>{const fresh=makeCompany();setCompany(fresh);setWorkspace(emptyWorkspace(fresh));}}>New company</button></div>
    {saved.length>0&&<div className="mb-3 text-[12px] text-secondary">Reopen workspace: {saved.map(item=><button key={item.company.id} className="ml-2 rounded border border-subtle px-2 py-1" onClick={()=>{setCompany(item.company);setWorkspace(item);}}>{item.company.profile.companyName}</button>)}</div>}
    <div className="mb-3 grid gap-2 text-[12px] md:grid-cols-3"><div className="rounded border border-subtle p-2">{workspace.sources.length} files · {workspace.datasets.length} datasets</div><div className="rounded border border-subtle p-2">{workspace.mappings.filter(m=>m.status==="mapped").length} confirmed field mappings</div><div className="rounded border border-subtle p-2"><Badge tone={blockers.length?"negative":"positive"}>{blockers.length?`${blockers.length} blocking`:"Ready"}</Badge> · {result.reconciliations.length} checks</div></div>
    {workspace.datasets.map(dataset=>{const type=dataset.confirmedType??dataset.inferred.type;const source=workspace.sources.find(s=>s.id===dataset.sourceFileId);const range=dataset.tableRange;return <section key={dataset.id} className="mb-3 rounded border border-subtle p-3 text-[12px] text-secondary"><div className="flex flex-wrap justify-between gap-2"><span className="text-primary">{source?.filename} · {dataset.sourceSheet} · {dataset.rows.length.toLocaleString()} rows</span><Badge tone={range?.requiresConfirmation&&!dataset.rangeConfirmed?"caution":"neutral"}>{dataset.inferred.type} · {Math.round(dataset.inferred.confidence*100)}%</Badge></div><div className="mt-2 flex flex-wrap gap-3"><label>Dataset type <select className="ml-1 rounded border border-subtle bg-canvas p-1" value={type} onChange={e=>updateDataset(dataset.id,d=>({...d,confirmedType:e.target.value as DatasetType}))}>{(["finance_actual","budget","forecast","sales","financial_calendar","gl_mapping","ignored","unknown"] as DatasetType[]).map(x=><option key={x}>{x}</option>)}</select></label><span>{dataset.inferred.reasons.join("; ")}</span></div>
      {range&&<div className="mt-2 rounded bg-subtle/40 p-2"><div className="flex flex-wrap gap-2">{(["headerRow","startRow","endRow","startColumn","endColumn"] as const).map(field=><label key={field}>{field}<input className="ml-1 w-14 rounded border border-subtle bg-canvas p-1" type="number" min="1" value={range[field]??1} onChange={e=>changeRange(dataset.id,field,Number(e.target.value))}/></label>)}<Badge tone={dataset.rangeConfirmed?"positive":range.requiresConfirmation?"caution":"neutral"}>{dataset.rangeConfirmed?"Confirmed":range.requiresConfirmation?"Needs Review":"Auto-detected"}</Badge>{range.requiresConfirmation&&!dataset.rangeConfirmed&&<button className="rounded border border-subtle px-2" onClick={()=>updateDataset(dataset.id,d=>({...d,rangeConfirmed:true}))}>Confirm selected range</button>}</div><div className="mt-2 max-h-28 overflow-auto font-mono text-[10px]">{(dataset.rawGrid??[]).slice(Math.max(0,range.headerRow-2),Math.min(dataset.rawGrid?.length??0,range.endRow+2)).map((row,i)=>{const rowNo=Math.max(0,range.headerRow-2)+i+1;return <div key={rowNo} className={`${rowNo===range.headerRow?"bg-accent/10 font-bold text-primary":""} ${rowNo>=range.startRow&&rowNo<=range.endRow?"text-secondary":"text-tertiary"}`}>{rowNo}: {JSON.stringify(row.slice((range.startColumn??1)-1,range.endColumn))}</div>;})}</div></div>}
      {(["finance_actual","budget","forecast"] as DatasetType[]).includes(type)&&<ScenarioReview datasetId={dataset.id} workspace={workspace} onChange={scenarios=>setWorkspace(w=>({...w,scenarios}))}/>}
      <details className="mt-2"><summary className="cursor-pointer text-primary">Field mapping review ({dataset.columns.length})</summary><div className="mt-2 max-h-64 overflow-auto"><table className="w-full text-left"><thead><tr><th>Source column</th><th>Type</th><th>Canonical field</th><th>Confidence</th><th>Status</th><th>Samples</th></tr></thead><tbody>{dataset.columns.map(column=>{const mapping=workspace.mappings.find(m=>m.datasetId===dataset.id&&m.sourceColumn===column.name);return <tr key={column.name} className="border-t border-subtle"><td>{column.name}</td><td>{column.inferredType}</td><td><select className="rounded border border-subtle bg-canvas p-1" value={mapping?.canonicalField??"ignore"} onChange={e=>setWorkspace(w=>({...w,mappings:w.mappings.map(m=>m.id===mapping?.id?{...m,canonicalField:e.target.value as CanonicalField,status:e.target.value==="ignore"?"ignored":"mapped"}:m)}))}>{fields.map(f=><option key={f}>{f}</option>)}</select></td><td>{mapping?.confidence?`${Math.round(mapping.confidence*100)}%`:"—"}</td><td>{mapping?.status??"Suggested"}</td><td>{column.samples.slice(0,2).map(String).join(", ")}</td></tr>;})}</tbody></table></div></details>
    </section>;})}
    {workspace.datasets.some(d=>d.wideUnpivot)&&<div className="mb-3 rounded border border-subtle p-3 text-[12px]">Wide-table identifier/value selection is retained in workspace configuration.</div>}
    <HierarchyRoleReview workspace={workspace} onChange={hierarchyRoles=>setWorkspace(w=>({...w,hierarchyRoles}))}/>
    {blockers.length>0&&<div className="mt-3 rounded border border-negative p-3 text-[12px] text-negative">{blockers.map(issue=><div key={issue.id}>{issue.message}</div>)}</div>}
    <div className="mt-4 flex gap-2"><button className="h-8 rounded bg-accent px-3 text-[12px] text-white disabled:opacity-40" disabled={!result.dataset||blockers.length>0} onClick={()=>result.dataset&&activateDataset(result.dataset)}><CheckCircle2 className="mr-1 inline" size={14}/>Activate reporting dataset</button><button className="h-8 rounded border border-subtle px-3 text-[12px]" onClick={activateDefaultDataset}>Switch to demo</button></div>
  </PanelBody></Panel>;
}
function ScenarioReview({datasetId,workspace,onChange}:{datasetId:string;workspace:ImportWorkspace;onChange:(value:ImportWorkspace["scenarios"])=>void}){const setup=workspace.scenarios.find(s=>s.datasetId===datasetId);return <div className="mt-2 flex flex-wrap items-center gap-2 text-[12px]"><span>Scenario</span><select className="rounded border border-subtle bg-canvas p-1" value={setup?.kind??""} onChange={e=>{const kind=e.target.value as "actual"|"budget"|"forecast";onChange([...workspace.scenarios.filter(s=>s.datasetId!==datasetId),{datasetId,scenarioId:kind,label:kind==="budget"?"Original Budget":kind,kind,version:kind==="budget"?"Original Budget":undefined}]);}}><option value="">Confirm scenario…</option><option value="actual">Actual</option><option value="budget">Budget / Original Budget</option><option value="forecast">Forecast</option></select><Badge tone={setup?"positive":"caution"}>{setup?"Confirmed":"Required"}</Badge></div>}
