import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Upload } from "lucide-react";
import { Panel, PanelBody, PanelHeader } from "@/components/ui/Panel";
import { Badge } from "@/components/ui/Badge";
import { stageLocalFile, suggestFieldMappings, buildImportedDataset, IndexedDbImportWorkspaceStore, type DatasetType, type ImportWorkspace, type IngestionCompany } from "@/domain/ingestion";
import { useReportingDataController } from "@/app/providers/ReportingDataProvider";

const makeCompany = (): IngestionCompany => ({ id: crypto.randomUUID(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), profile: { companyName: "New company", shortName: "New company", reportingCurrency: "AUD", currencySymbol: "$", locale: "en-AU", defaultScale: "millions", fiscalCalendar: { periodicity: "monthly", fiscalYearStartMonth: 1, fiscalYearLabel: "endYear" } } });

export function OnboardingPanel() {
  const { activateDataset, activateDefaultDataset } = useReportingDataController();
  const [company, setCompany] = useState<IngestionCompany>(makeCompany);
  const [workspace, setWorkspace] = useState<ImportWorkspace>({ company, sources: [], datasets: [], mappings: [], rules: [], customDimensions: [], scenarios: [], calendar: { fiscalYearStartMonth: 1, fiscalYearLabel: "endYear" }, issues: [], reconciliations: [] });
  const store = useMemo(() => new IndexedDbImportWorkspaceStore(), []);
  const [savedWorkspaces, setSavedWorkspaces] = useState<ImportWorkspace[]>([]);
  useEffect(() => { void store.list().then(setSavedWorkspaces); }, [store]);
  useEffect(() => { void store.save({ ...workspace, company }); }, [workspace, company, store]);
  const result = useMemo(() => buildImportedDataset({ ...workspace, company }), [workspace, company]);
  const upload = async (files: FileList | null) => { if (!files) return; const staged = await Promise.all([...files].map((file) => stageLocalFile(company.id, file))); setWorkspace((current) => ({ ...current, sources: [...current.sources, ...staged.map((item) => item.source)], datasets: [...current.datasets, ...staged.flatMap((item) => item.datasets)], mappings: [...current.mappings, ...staged.flatMap((item) => item.datasets.flatMap((dataset) => suggestFieldMappings(dataset.id, dataset.columns.map((column) => column.name))))] })); };
  const blocking = result.issues.filter((issue) => issue.severity === "error").length;
  const canActivate = workspace.datasets.length > 0 && !!result.dataset && blocking === 0;
  const updateDataset = (id: string, update: (dataset: ImportWorkspace["datasets"][number]) => ImportWorkspace["datasets"][number]) => setWorkspace(current => ({ ...current, datasets: current.datasets.map(dataset => dataset.id === id ? update(dataset) : dataset) }));
  return <Panel>
    <PanelHeader title="Company onboarding" meta="Local-only staging → mapping → validation → reporting dataset" />
    <PanelBody>
      <div className="flex flex-wrap items-end gap-3 mb-4">
        <label className="text-[11px] text-secondary">Company name<input className="mt-1 block h-8 w-48 rounded border border-subtle bg-canvas px-2 text-primary" value={company.profile.companyName} onChange={(event) => setCompany({ ...company, profile: { ...company.profile, companyName: event.target.value, shortName: event.target.value } })} /></label>
        <label className="text-[11px] text-secondary">Currency<input className="mt-1 block h-8 w-20 rounded border border-subtle bg-canvas px-2 text-primary" value={company.profile.reportingCurrency} onChange={(event) => setCompany({ ...company, profile: { ...company.profile, reportingCurrency: event.target.value } })} /></label>
        <label className="text-[11px] text-secondary">Fiscal year starts<input type="number" min="1" max="12" className="mt-1 block h-8 w-20 rounded border border-subtle bg-canvas px-2 text-primary" value={company.profile.fiscalCalendar.fiscalYearStartMonth} onChange={(event) => setCompany({ ...company, profile: { ...company.profile, fiscalCalendar: { ...company.profile.fiscalCalendar, fiscalYearStartMonth: Number(event.target.value) } } })} /></label>
        <label className="inline-flex h-8 items-center gap-2 rounded border border-subtle px-3 text-[12px] text-secondary cursor-pointer"><Upload size={14}/> Upload CSV / XLSX<input className="hidden" type="file" accept=".csv,.xlsx,.xls" multiple onChange={(event) => void upload(event.target.files)} /></label>
        <button className="h-8 rounded border border-subtle px-3 text-[12px] text-secondary" onClick={() => { const next=makeCompany(); setCompany(next); setWorkspace({ company:next, sources:[], datasets:[], mappings:[], rules:[], hierarchyRoles:[], customDimensions:[], scenarios:[], calendar:{ fiscalYearStartMonth:1, fiscalYearLabel:"endYear" }, issues:[], reconciliations:[] }); }}>New company</button>
      </div>
      {savedWorkspaces.length > 0 && <div className="mb-4 text-[12px] text-secondary">Reopen: {savedWorkspaces.map(saved => <button key={saved.company.id} className="ml-2 rounded border border-subtle px-2 py-1" onClick={() => { setCompany(saved.company); setWorkspace(saved); }}>{saved.company.profile.companyName}</button>)}</div>}
      <div className="grid grid-cols-1 gap-2 text-[12px] md:grid-cols-3">
        <div className="rounded border border-subtle p-3"><div className="eyebrow">1 Upload</div><div className="mt-1 text-primary">{workspace.sources.length} files · {workspace.datasets.length} datasets</div></div>
        <div className="rounded border border-subtle p-3"><div className="eyebrow">2 Classify & map</div><div className="mt-1 text-primary">{workspace.datasets.filter((dataset) => dataset.inferred.type !== "unknown").length} classified · {workspace.mappings.filter((mapping) => mapping.status === "mapped").length} mapped</div></div>
        <div className="rounded border border-subtle p-3"><div className="eyebrow">3 Validate & activate</div><div className="mt-1 flex items-center gap-2 text-primary"><Badge tone={blocking ? "negative" : "positive"}>{blocking ? `${blocking} blocking` : "Ready"}</Badge>{result.reconciliations.length} reconciliations</div></div>
      </div>
      {workspace.datasets.length > 0 && <div className="mt-4 space-y-3">{workspace.datasets.map((dataset) => {
        const type = dataset.confirmedType ?? dataset.inferred.type;
        const source = workspace.sources.find(item => item.id === dataset.sourceFileId);
        return <div key={dataset.id} className="rounded border border-subtle p-3 text-[12px] text-secondary">
          <div className="flex flex-wrap items-center justify-between gap-2"><span className="text-primary">{source?.filename} · {dataset.sourceSheet} · {dataset.rows.length.toLocaleString()} rows</span><Badge tone={type === "unknown" ? "caution" : "neutral"}>{dataset.inferred.type} · {Math.round(dataset.inferred.confidence * 100)}%</Badge></div>
          <div className="mt-2 flex flex-wrap items-center gap-2"><label>Confirmed type <select className="ml-1 rounded border border-subtle bg-canvas p-1" value={type} onChange={e => updateDataset(dataset.id, d => ({ ...d, confirmedType: e.target.value as DatasetType }))}>{(["finance_actual","budget","forecast","sales","financial_calendar","gl_mapping","ignored","unknown"] as DatasetType[]).map(option => <option key={option}>{option}</option>)}</select></label><span className="text-tertiary">{dataset.inferred.reasons.join("; ")}</span></div>
          {(["finance_actual","budget","forecast"] as DatasetType[]).includes(type) && <label className="mt-2 block">Scenario <select className="ml-1 rounded border border-subtle bg-canvas p-1" value={workspace.scenarios.find(s => s.datasetId === dataset.id)?.kind ?? (type === "budget" ? "budget" : "actual")} onChange={e => setWorkspace(current => ({ ...current, scenarios: [...current.scenarios.filter(s => s.datasetId !== dataset.id), { datasetId: dataset.id, scenarioId: e.target.value, kind: e.target.value as "actual" | "budget" | "forecast", label: e.target.value === "budget" ? "Original Budget" : e.target.value === "actual" ? "Actual" : "Forecast", version: e.target.value === "budget" ? "Original Budget" : undefined }] }))}><option value="actual">Actual</option><option value="budget">Budget / Original Budget</option><option value="forecast">Forecast</option></select></label>}
          {dataset.tableRange && <div className="mt-2 rounded bg-subtle/40 p-2">Source range: header {dataset.tableRange.headerRow}, data rows {dataset.tableRange.startRow}–{dataset.tableRange.endRow}, columns {dataset.tableRange.startColumn ?? 1}–{dataset.tableRange.endColumn ?? dataset.columns.length}. {dataset.tableRange.requiresConfirmation && <><button className="ml-2 rounded border border-subtle px-2 py-1" onClick={() => updateDataset(dataset.id, d => ({ ...d, rangeConfirmed: true }))}>Confirm range</button><span className="ml-2 text-negative">confirmation required</span></>}<div className="mt-1 max-h-20 overflow-auto text-tertiary">Preview: {JSON.stringify(dataset.rows.slice(0, 2))}</div></div>}
          {type !== "ignored" && dataset.columns.length > 1 && <div className="mt-2"><button className="rounded border border-subtle px-2 py-1" onClick={() => updateDataset(dataset.id, d => ({ ...d, wideUnpivot: d.wideUnpivot ? undefined : { identifierColumns: [], valueColumns: [], periodFromColumn: true, valueField: "amount" } }))}>{dataset.wideUnpivot ? "Use source rows" : "Configure wide table / unpivot"}</button>{dataset.wideUnpivot && <div className="mt-2 grid gap-1"><span>Identifier columns</span>{dataset.columns.map(column => <label key={column.name}><input type="checkbox" checked={dataset.wideUnpivot!.identifierColumns.includes(column.name)} onChange={() => updateDataset(dataset.id, d => { const config=d.wideUnpivot!; const ids=config.identifierColumns.includes(column.name)?config.identifierColumns.filter(name=>name!==column.name):[...config.identifierColumns,column.name]; return {...d,wideUnpivot:{...config,identifierColumns:ids,valueColumns:config.valueColumns.filter(name=>name!==column.name)}}; })}/> {column.name}</label>)}<span className="mt-1">Value / period columns</span>{dataset.columns.map(column => <label key={`value-${column.name}`}><input type="checkbox" checked={dataset.wideUnpivot!.valueColumns.includes(column.name)} onChange={() => updateDataset(dataset.id, d => { const config=d.wideUnpivot!; const values=config.valueColumns.includes(column.name)?config.valueColumns.filter(name=>name!==column.name):[...config.valueColumns,column.name]; return {...d,wideUnpivot:{...config,valueColumns:values,identifierColumns:config.identifierColumns.filter(name=>name!==column.name)}}; })}/> {column.name}</label>)}</div>}</div>}
        </div>;
      })}</div>}
      <div className="mt-4 flex items-center gap-3"><button className="h-8 rounded bg-accent px-3 text-[12px] font-medium text-white disabled:opacity-40" disabled={!canActivate} onClick={() => result.dataset && activateDataset(result.dataset)}>Activate reporting dataset</button><button className="h-8 rounded border border-subtle px-3 text-[12px] text-secondary" onClick={activateDefaultDataset}>Switch to demo dataset</button>{canActivate && <span className="inline-flex items-center gap-1 text-[12px] text-positive"><CheckCircle2 size={14}/> Ready to activate</span>}</div>
    </PanelBody>
  </Panel>;
}
