import type { Account, FinanceRecord } from "@/domain/models";
import { resolveAccountRule } from "../mapping";
import type { MappingRule } from "../types";
import type { ImportTransformationContext } from "./context";
import { resolveScenario } from "./scenarios";
import { amount, fieldValue, prepareDatasetRows, text } from "./shared";
import type { DimensionTokens } from "./dimensions";
import { remember } from "./dimensions";

export interface FinanceTransformResult { accounts:Map<string,Account>; records:FinanceRecord[]; magnitude:Map<string,number>; raw:number; sign:number; mapped:number; unmapped:number; unresolved:number; }
export function transformFinanceSources(context:ImportTransformationContext,rules:MappingRule[],tokens?:DimensionTokens):FinanceTransformResult { const accounts=new Map<string,Account>(),records:FinanceRecord[]=[],magnitude=new Map<string,number>();let raw=0,sign=0,mapped=0,unmapped=0,unresolved=0;
  for(const dataset of context.financeDatasets){const mappings=context.workspace.mappings.filter(mapping=>mapping.datasetId===dataset.id),scenario=resolveScenario(context.workspace,dataset.id)!;for(const [index,row] of prepareDatasetRows(dataset).entries()){const accountId=text(fieldValue(row,mappings,"accountId")),source=amount(fieldValue(row,mappings,"amount")??row[dataset.wideUnpivot?.valueField??"amount"]);if(!accountId||!Number.isFinite(source))continue;raw+=source;magnitude.set(accountId,(magnitude.get(accountId)??0)+Math.abs(source));const rule=resolveAccountRule(accountId,text(fieldValue(row,mappings,"accountName")),rules),canonical=source*(rule?.sourceMultiplier??1);sign+=canonical;if(!rule||rule.line==="unconfirmed"){unmapped+=canonical;unresolved+=Math.abs(source);accounts.set(accountId,{id:accountId,name:accountId,externalId:accountId,mappingStatus:"unmapped",statement:"pnl",line:"unconfirmed",sign:1,accountMappingStatus:"Needs Review"});continue;}mapped+=canonical;const entityId=text(fieldValue(row,mappings,"entityId"))||"company",costCentreId=text(fieldValue(row,mappings,"costCentreId"))||undefined,departmentId=text(fieldValue(row,mappings,"departmentId"))||undefined;if(tokens){remember(tokens.entities,entityId);if(costCentreId)remember(tokens.costCentres,costCentreId);if(departmentId)remember(tokens.departments,departmentId);}accounts.set(accountId,{id:accountId,name:text(fieldValue(row,mappings,"accountName"))||accountId,externalId:accountId,mappingStatus:"mapped",statement:rule.statement,line:rule.line,sign:rule.sign,reportingHierarchy:rule.reportingHierarchy,calculationRole:rule.calculationRole,mappingSource:rule.mappingSource,accountMappingStatus:rule.mappingStatus,sourceMultiplier:rule.sourceMultiplier});records.push({periodId:text(fieldValue(row,mappings,"period")),entityId,costCentreId,departmentId,accountId,scenarioValues:[{scenarioId:scenario.scenarioId,value:canonical}],...(scenario.kind==="actual"?{actual:canonical}:scenario.kind==="budget"?{budget:canonical}:{forecast:canonical}),lineage:{sourceImportId:dataset.sourceFileId,sourceRow:index+1,mappingVersion:rule.id}});}}
  return{accounts,records,magnitude,raw,sign,mapped,unmapped,unresolved}; }
