import type { SalesRecord } from "@/domain/models";
import type { ImportTransformationContext } from "./context";
import type { FieldMapping } from "../types";
import type { DimensionTokens } from "./dimensions";
import { remember } from "./dimensions";
import { amount, fieldValue, prepareDatasetRows, text } from "./shared";

export interface SalesTransformResult { salesRecords:SalesRecord[]; weeklySalesRecords:SalesRecord[]; issues:string[]; }
const optional=(row:Record<string,unknown>,mappings:FieldMapping[],field:string)=>{const value=text(fieldValue(row,mappings,field));return value||undefined;};
export function transformSalesSources(context:ImportTransformationContext, periodIds:Set<string>, weekLookup:Map<string,string>, tokens:DimensionTokens):SalesTransformResult{const salesRecords:SalesRecord[]=[],weeklySalesRecords:SalesRecord[]=[],issues:string[]=[];for(const dataset of context.datasets.filter(d=>(d.confirmedType??d.inferred.type)==="sales")){const mappings=context.workspace.mappings.filter(mapping=>mapping.datasetId===dataset.id);for(const row of prepareDatasetRows(dataset)){const revenue=amount(fieldValue(row,mappings,"revenue"));const entity=text(fieldValue(row,mappings,"entityId"))||"company";const rawPeriod=text(fieldValue(row,mappings,"period")||fieldValue(row,mappings,"date"));if(!Number.isFinite(revenue)){issues.push(`${dataset.id}: non-numeric revenue`);continue;}remember(tokens.entities,entity);const common={entityId:entity,revenue,locationId:optional(row,mappings,"locationId"),channelId:optional(row,mappings,"channelId"),productId:optional(row,mappings,"productId"),customerId:optional(row,mappings,"customerId"),cost:Number.isFinite(amount(fieldValue(row,mappings,"cost")))?amount(fieldValue(row,mappings,"cost")):undefined,units:Number.isFinite(amount(fieldValue(row,mappings,"units")))?amount(fieldValue(row,mappings,"units")):undefined,orders:Number.isFinite(amount(fieldValue(row,mappings,"orders")))?amount(fieldValue(row,mappings,"orders")):undefined};if(common.locationId)remember(tokens.locations,common.locationId);if(common.channelId)remember(tokens.channels,common.channelId);if(common.productId)remember(tokens.products,common.productId);if(common.customerId)remember(tokens.customers,common.customerId);const week=weekLookup.get(rawPeriod)||weekLookup.get(rawPeriod.replace(/^Week\s*/i,"W").toUpperCase());if(week)weeklySalesRecords.push({...common,periodId:week});else if(periodIds.has(rawPeriod))salesRecords.push({...common,periodId:rawPeriod});else issues.push(`${dataset.id}: unresolved sales period ${rawPeriod||"(blank)"}`);}}return{salesRecords,weeklySalesRecords,issues};}
