import type { MetricDefinition, MetricRegistry } from "./types";

/**
 * METRIC REGISTRY
 * ---------------------------------------------------------------------------
 * The contract between data and UI. A component is handed a metric id and a
 * value; everything about how that value reads — its unit, its precision,
 * whether a rise is good — comes from here. Adding a metric for a new client
 * is a registry entry, not a component change.
 */

const define = (m: MetricDefinition): MetricDefinition => m;

export const metrics: MetricRegistry = Object.fromEntries(
  [
    // ---- Financial -------------------------------------------------------
    define({
      id: "revenue",
      name: "Revenue",
      format: "currency",
      favourableDirection: "up",
      aggregation: "sum",
      domain: "financial",
      description: "Net sales after returns and trade discounts.",
    }),
    define({
      id: "costOfSales",
      name: "Cost of Sales",
      format: "currency",
      favourableDirection: "down",
      aggregation: "sum",
      domain: "financial",
    }),
    define({
      id: "grossProfit",
      name: "Gross Profit",
      format: "currency",
      favourableDirection: "up",
      aggregation: "sum",
      domain: "financial",
      description: "Revenue less cost of sales.",
    }),
    define({
      id: "grossMargin",
      name: "Gross Margin",
      format: "percentage",
      favourableDirection: "up",
      aggregation: "weightedAverage",
      precision: 1,
      deltaFormat: "bps",
      domain: "financial",
      description: "Gross profit as a percentage of revenue.",
    }),
    define({
      id: "contributionMargin",
      name: "Contribution Margin",
      format: "percentage",
      favourableDirection: "up",
      aggregation: "weightedAverage",
      precision: 1,
      deltaFormat: "bps",
      domain: "financial",
    }),
    define({
      id: "operatingCosts",
      name: "Operating Costs",
      format: "currency",
      // Higher cost is adverse. This is why favourableDirection exists.
      favourableDirection: "down",
      aggregation: "sum",
      domain: "financial",
    }),
    define({
      id: "ebitda",
      name: "EBITDA",
      format: "currency",
      favourableDirection: "up",
      aggregation: "sum",
      domain: "financial",
      description: "Earnings before interest, tax, depreciation and amortisation.",
    }),
    define({
      id: "ebitdaMargin",
      name: "EBITDA Margin",
      format: "percentage",
      favourableDirection: "up",
      aggregation: "weightedAverage",
      precision: 1,
      deltaFormat: "bps",
      domain: "financial",
    }),
    define({
      id: "ebit",
      name: "EBIT",
      format: "currency",
      favourableDirection: "up",
      aggregation: "sum",
      domain: "financial",
    }),
    define({
      id: "netProfit",
      name: "Net Profit",
      format: "currency",
      favourableDirection: "up",
      aggregation: "sum",
      domain: "financial",
    }),
    define({
      id: "depreciationAmortisation",
      name: "Depreciation & Amortisation",
      shortName: "D&A",
      format: "currency",
      favourableDirection: "neutral",
      aggregation: "sum",
      domain: "financial",
    }),

    // ---- Balance sheet / working capital ---------------------------------
    define({
      id: "cash",
      name: "Cash",
      format: "currency",
      favourableDirection: "up",
      aggregation: "last",
      domain: "workingCapital",
      description: "Cash and cash equivalents at period end.",
    }),
    define({
      id: "inventory",
      name: "Inventory",
      format: "currency",
      // Deliberately neutral: inventory build can be planned or a problem.
      favourableDirection: "neutral",
      aggregation: "last",
      domain: "workingCapital",
    }),
    define({
      id: "tradeReceivables",
      name: "Trade Receivables",
      shortName: "Receivables",
      format: "currency",
      favourableDirection: "neutral",
      aggregation: "last",
      domain: "workingCapital",
    }),
    define({
      id: "tradePayables",
      name: "Trade Payables",
      shortName: "Payables",
      format: "currency",
      favourableDirection: "neutral",
      aggregation: "last",
      domain: "workingCapital",
    }),
    define({
      id: "netAssets",
      name: "Net Assets",
      format: "currency",
      favourableDirection: "up",
      aggregation: "last",
      domain: "workingCapital",
    }),
    define({
      id: "netDebt",
      name: "Net Debt",
      format: "currency",
      favourableDirection: "down",
      aggregation: "last",
      domain: "workingCapital",
      description: "Borrowings and leases less cash.",
    }),
    define({
      id: "workingCapital",
      name: "Working Capital",
      format: "currency",
      favourableDirection: "neutral",
      aggregation: "last",
      domain: "workingCapital",
    }),
    define({
      id: "operatingCashFlow",
      name: "Operating Cash Flow",
      format: "currency",
      favourableDirection: "up",
      aggregation: "sum",
      domain: "workingCapital",
    }),
    define({
      id: "freeCashFlow",
      name: "Free Cash Flow",
      format: "currency",
      favourableDirection: "up",
      aggregation: "sum",
      domain: "workingCapital",
    }),
    define({
      id: "dso",
      name: "Days Sales Outstanding",
      shortName: "DSO",
      format: "days",
      favourableDirection: "down",
      aggregation: "derived",
      domain: "workingCapital",
      description: "Trade receivables ÷ revenue × days in period.",
    }),
    define({
      id: "dpo",
      name: "Days Payables Outstanding",
      shortName: "DPO",
      format: "days",
      // Longer payment terms help cash but strain suppliers — not a scored metric.
      favourableDirection: "neutral",
      aggregation: "derived",
      domain: "workingCapital",
      description: "Trade payables ÷ cost of sales × days in period.",
    }),
    define({
      id: "dio",
      name: "Inventory Days",
      shortName: "DIO",
      format: "days",
      favourableDirection: "down",
      aggregation: "derived",
      domain: "workingCapital",
      description: "Inventory ÷ cost of sales × days in period.",
    }),
    define({
      id: "cashConversionCycle",
      name: "Cash Conversion Cycle",
      shortName: "CCC",
      format: "days",
      favourableDirection: "down",
      aggregation: "derived",
      domain: "workingCapital",
      description: "DSO + DIO − DPO.",
    }),
    define({
      id: "currentRatio",
      name: "Current Ratio",
      format: "times",
      favourableDirection: "up",
      aggregation: "derived",
      precision: 2,
      domain: "workingCapital",
    }),
    define({
      id: "quickRatio",
      name: "Quick Ratio",
      format: "times",
      favourableDirection: "up",
      aggregation: "derived",
      precision: 2,
      domain: "workingCapital",
    }),
    define({
      id: "cashRatio",
      name: "Cash Ratio",
      format: "times",
      favourableDirection: "up",
      aggregation: "derived",
      precision: 2,
      domain: "workingCapital",
    }),
    define({
      id: "netDebtToEbitda",
      name: "Net Debt / EBITDA",
      format: "times",
      favourableDirection: "down",
      aggregation: "derived",
      precision: 2,
      domain: "workingCapital",
    }),

    // ---- Sales -----------------------------------------------------------
    define({
      id: "totalSales",
      name: "Total Sales",
      format: "currency",
      favourableDirection: "up",
      aggregation: "sum",
      domain: "sales",
    }),
    define({
      id: "likeForLikeSales",
      name: "Like-for-Like Sales",
      shortName: "LFL Sales",
      format: "currency",
      favourableDirection: "up",
      aggregation: "sum",
      domain: "sales",
      description: "Sales from locations trading in both comparative periods.",
    }),
    define({
      id: "likeForLikeGrowth",
      name: "Like-for-Like Growth",
      shortName: "LFL Growth",
      format: "percentage",
      favourableDirection: "up",
      aggregation: "derived",
      precision: 1,
      domain: "sales",
    }),
    define({
      id: "averageTransactionValue",
      name: "Average Transaction Value",
      shortName: "ATV",
      format: "currency",
      favourableDirection: "up",
      aggregation: "weightedAverage",
      precision: 2,
      scale: "units",
      domain: "sales",
    }),
    define({
      id: "units",
      name: "Units Sold",
      format: "number",
      favourableDirection: "up",
      aggregation: "sum",
      domain: "sales",
    }),
    define({
      id: "orders",
      name: "Orders",
      format: "number",
      favourableDirection: "up",
      aggregation: "sum",
      domain: "sales",
    }),
    define({
      id: "transactions",
      name: "Transactions",
      format: "number",
      favourableDirection: "up",
      aggregation: "sum",
      domain: "sales",
    }),
    define({
      id: "conversion",
      name: "Conversion",
      format: "percentage",
      favourableDirection: "up",
      aggregation: "weightedAverage",
      precision: 1,
      deltaFormat: "bps",
      domain: "operational",
    }),
    define({
      id: "traffic",
      name: "Traffic",
      format: "number",
      favourableDirection: "up",
      aggregation: "sum",
      domain: "operational",
    }),
    define({
      id: "unitsPerTransaction",
      name: "Units per Transaction",
      shortName: "UPT",
      format: "number",
      favourableDirection: "up",
      aggregation: "weightedAverage",
      precision: 2,
      scale: "units",
      domain: "operational",
    }),
    define({
      id: "discountRate",
      name: "Discount Rate",
      format: "percentage",
      favourableDirection: "down",
      aggregation: "weightedAverage",
      precision: 1,
      deltaFormat: "bps",
      domain: "sales",
    }),
    define({
      id: "salesPerLabourHour",
      name: "Sales per Labour Hour",
      format: "currency",
      favourableDirection: "up",
      aggregation: "weightedAverage",
      precision: 2,
      scale: "units",
      domain: "operational",
    }),
    define({
      id: "nps",
      name: "Net Promoter Score",
      shortName: "NPS",
      format: "number",
      favourableDirection: "up",
      aggregation: "average",
      precision: 0,
      scale: "units",
      domain: "operational",
    }),

    // ---- Forecast --------------------------------------------------------
    define({
      id: "fullYearForecast",
      name: "Full-Year Forecast",
      format: "currency",
      favourableDirection: "up",
      aggregation: "sum",
      domain: "forecast",
    }),
    define({
      id: "forecastAccuracy",
      name: "Forecast Accuracy",
      format: "percentage",
      favourableDirection: "up",
      aggregation: "average",
      precision: 1,
      domain: "forecast",
      description: "1 − mean absolute percentage error of the prior reforecast.",
    }),
    define({
      id: "revenueRunRate",
      name: "Revenue Run Rate",
      format: "currency",
      favourableDirection: "up",
      aggregation: "derived",
      domain: "forecast",
    }),
    define({
      id: "forecastChange",
      name: "Forecast Change",
      format: "currency",
      favourableDirection: "up",
      aggregation: "derived",
      domain: "forecast",
    }),
    define({
      id: "recoveryRequired",
      name: "Recovery Required",
      format: "currency",
      favourableDirection: "down",
      aggregation: "derived",
      domain: "forecast",
      description: "Gap to plan that the remaining periods must close.",
    }),
  ].map((m) => [m.id, m]),
);

/** Look up a metric, failing loudly rather than rendering a mystery number. */
export function getMetric(id: string): MetricDefinition {
  const metric = metrics[id];
  if (!metric) {
    throw new Error(
      `Unknown metric "${id}". Register it in domain/metrics/registry.ts.`,
    );
  }
  return metric;
}

export function tryGetMetric(id: string): MetricDefinition | undefined {
  return metrics[id];
}
